/* Guest capability rooms; server-authoritative shot scoring; automatic 3-second table refresh. */
(function(root){'use strict';var DT=root.DT,endpoint='https://ovryjrniokyxiwesfsqw.supabase.co/functions/v1/duran-top-live',state=null,callback=function(){},status=function(){},timer=null,ready=null,pending=null;
function get(k){try{return JSON.parse(root.localStorage.getItem(k));}catch(e){return null;}}function put(k,v){root.localStorage.setItem(k,JSON.stringify(v));}
var token=get('dt_live_token');if(!token){token=Array.from(root.crypto.getRandomValues(new Uint8Array(32)),function(n){return n.toString(16).padStart(2,'0');}).join('');put('dt_live_token',token);}
async function api(body){var controller=new AbortController(),timeout=root.setTimeout(function(){controller.abort();},12000);try{var r=await root.fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','x-player-token':token},body:JSON.stringify(body),signal:controller.signal}),data=await r.json();if(!r.ok)throw Error(data.error||'Bağlantı kurulamadı.');return data;}finally{root.clearTimeout(timeout);}}
function set(s){state=s;put('dt_live_room',s.room.id);callback(s);status('Canlı kupa · skorlar otomatik güncelleniyor');return s;}
function current(){return state&&state.players.find(function(p){return p.mine;});}
function schedule(){root.clearTimeout(timer);timer=root.setTimeout(async function(){if(state&&!root.document.hidden){try{set(await api({action:'state',room:state.room.id}));}catch(e){status('Bağlantı bekleniyor · skorlar korunuyor');}}schedule();},3000);}
function init(onState,onStatus){callback=onState;status=onStatus;var query=new URLSearchParams(root.location.search),id=query.get('oda')||get('dt_live_room');pending=get('dt_live_pending');status('Canlı kupaya bağlanılıyor…');ready=(async function(){if(id){try{return set(await api({action:'state',room:id}));}catch(e){if(query.get('oda'))throw e;}}return set(await api({action:'create'}));})().then(function(s){schedule();return s;}).catch(function(e){ready=null;status(e.message);throw e;});return ready||init(callback,status);}
async function ensure(){if(state)return state;return ready||init(callback,status);}
async function create(){try{await ensure();}catch(e){}if(current()&&current().idx<5)throw Error('Önce devam eden turunu bitir.');pending=null;put('dt_live_pending',null);var s=set(await api({action:'create'}));ready=Promise.resolve(s);schedule();var url=new URL(root.location.href);url.searchParams.set('oda',s.room.id);url.searchParams.delete('kupa');root.history.replaceState(null,'',url);return s;}
async function join(player){await ensure();var s=set(await api({action:'join',room:state.room.id,player:player}));return s.players.find(function(p){return p.mine;});}
async function shot(player,idx,input){await ensure();if(pending&&(pending.room!==state.room.id||pending.player!==player||pending.idx!==idx)){pending=null;put('dt_live_pending',null);}if(!pending){pending={action:'shot',room:state.room.id,player:player,idx:idx,aim:input.aim,contact:input.contact,zaman:input.zaman};put('dt_live_pending',pending);}var result=await api(pending);pending=null;put('dt_live_pending',null);set(result.state);return result.entry;}
function records(){var records={};if(state)state.players.forEach(function(p){var entries=p.entries||[];
 // Başkasının turu bitmeden toplamı gizlidir (ortak kaleci koşulları sıra gelmeden öğretici olmasın): puan null, idx ilerlemeyi söyler.
 var hidden=!p.mine&&!p.ozet,summary=p.ozet||{puan:entries.reduce(function(t,x){return t+x.puan;},0),gol:entries.filter(function(x){return x.gol;}).length,yesil:entries.filter(function(x){return x.yesil;}).length};
 records[p.player]={id:p.player,idx:p.idx,puan:hidden?null:summary.puan,gol:hidden?0:summary.gol,yesil:hidden?0:summary.yesil};});return records;}
function allowed(player){var slot=state&&state.players.find(function(p){return p.player===player;});return !!state&&(!slot||(slot.mine&&slot.idx<5));}
function link(){return 'https://metoapps.github.io/DuranTop/?oda='+state.room.id+'&v=20261004e';}
DT.live={init:init,ensure:ensure,create:create,join:join,shot:shot,records:records,allowed:allowed,current:current,link:link,getState:function(){return state;}};
})(window);
