const vm=require('vm'),fs=require('fs'),assert=require('assert');const C=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');const elements={};
function el(id){return elements[id]||(elements[id]={hidden:false,style:{},classList:{toggle(){}},events:{},children:[],appendChild(c){this.children.push(c)},getAttribute(){return 0},getContext(){return C.createCanvas(220,220).getContext('2d')},addEventListener(k,v){(this.events[k]||=[]).push(v)},getBoundingClientRect(){return {left:5,top:10,width:195,height:422}},setPointerCapture(){}})}
const doc={readyState:'loading',getElementById:el,createElement:()=>el(Math.random()),querySelectorAll:()=>[],addEventListener(){}};let time=0,ready=true;const memory={};const root={document:doc,URLSearchParams,performance:{now:()=>time},navigator:{},location:{search:'?kupa=ABC123',reload(){}},localStorage:{getItem:k=>memory[k]||null,setItem:(k,v)=>memory[k]=v,removeItem:k=>delete memory[k]},requestAnimationFrame(f){root.frame=f},alert(){},btoa:s=>Buffer.from(s).toString('base64'),atob:s=>Buffer.from(s,'base64').toString()};vm.createContext(root);for(const n of ['ayar','veri','kaleci','ucus','fizik','puan'])vm.runInContext(fs.readFileSync(__dirname+'/../js/'+n+'.js','utf8'),root);const D=root.DT;D.cizim={ciz(){},kur(){},sahneKur(){},hazir:()=>ready,boyut:()=>({w:390,h:844}),ekranToKale:(x,y)=>({x:x/100,y:y/100})};D.ses={ayarla(){},cal(){}};vm.runInContext(fs.readFileSync(__dirname+'/../js/oyun.js','utf8'),root);D.oyun.baslat();const d=D.oyun._durum;function fire(id,k,v={}){for(const f of el(id).events[k]||[])f(v)}
fire('btnCubuk','click');for(const mode of ['resmi','antrenman']){d.faz='nisan';d.kilit=false;d.temasHazir=false;d.pos=D.AYAR.pozisyonlar[0];d.mod=mode;d.karakter='meto';d.idx=0;d.sonuclar=[];
fire('sahne','pointerdown',{clientX:105,clientY:65,pointerId:1});fire('sahne','pointerup');assert(d.kilit);assert(!el('temasPanel').hidden);assert(el('alt').hidden);fire('vurBtn','pointerdown',{isPrimary:true});assert.equal(d.faz,'nisan');fire('temasOnay','click');assert(d.temasHazir);assert(el('temasPanel').hidden);assert.equal(el('cubukKutu').hidden,mode!=='resmi');ready=false;fire('vurBtn','pointerdown',{isPrimary:true});assert.equal(d.faz,'nisan');ready=true;time=d.cubukBasla+400;fire('vurBtn','pointerdown',{isPrimary:true});assert.equal(d.faz,'vurus');const a=d.an;fire('vurBtn','pointerdown',{isPrimary:true});assert.strictEqual(d.an,a);}
console.log('PASS target → contact → timing; early/repeated press guards; mandatory official timing; asset guard; cup initialization');

fire('btnResmi','click');const button=el('secimIzgara').children[0];button.events.click[0]();
for(let i=0;i<5;i++){assert.equal(d.idx,i);fire('sahne','pointerdown',{clientX:105,clientY:65,pointerId:1});fire('sahne','pointerup');fire('temasOnay','click');time=d.cubukBasla+400;fire('vurBtn','pointerdown',{isPrimary:true});let saved=JSON.parse(memory.dt6_resmi);assert.equal(saved.idx,i+1);assert.equal(saved.sonuclar.length,i+1);time+=5000;root.frame();assert.equal(d.faz,'sonuc');fire('devamBtn','click');}
assert(!memory.dt6_resmi);const cup=JSON.parse(memory.dt6_kupa_ABC123);assert.equal(cup.meto.yesil,5);assert(Number.isInteger(cup.meto.puan));fire('btnResmi','click');assert(el('secimIzgara').children.slice(-5)[0].disabled);console.log('PASS complete official 5-shot cup; persisted single-count shots; green count independent of goals; completed player locked');
let imported={v:1,kod:'ABC123',r:{id:'lort',puan:220,gol:2,yesil:3}};root.prompt=()=> 'LORT sonucu DT6-'+root.btoa(JSON.stringify(imported));fire('sonucEkle','click');assert.equal(JSON.parse(memory.dt6_kupa_ABC123).lort.puan,220);imported.r.puan=500;fire('sonucEkle','click');assert.equal(JSON.parse(memory.dt6_kupa_ABC123).lort.puan,220);imported={v:0,kod:'ABC123',r:{id:'fero',puan:200,gol:2,yesil:3}};fire('sonucEkle','click');assert(!JSON.parse(memory.dt6_kupa_ABC123).fero);fire('yeniKupa','click');assert(/^[A-F0-9]{6}$/.test(el('kupaKod').value));console.log('PASS result-code import; duplicate player protection; physics-version rejection; new cup creation');
