(async()=>{
const vm=require('vm'),fs=require('fs'),assert=require('assert'),C=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas'),elements={};
function el(id){return elements[id]||(elements[id]={hidden:false,style:{},classList:{toggle(){}},events:{},children:[],appendChild(c){this.children.push(c)},getAttribute(){return 0},getContext(){return C.createCanvas(220,220).getContext('2d')},addEventListener(k,v){(this.events[k]||=[]).push(v)},getBoundingClientRect(){return {left:5,top:10,width:195,height:422}},setPointerCapture(){}})}
const doc={readyState:'loading',getElementById:el,createElement:()=>el(Math.random()),querySelectorAll:()=>[],addEventListener(){}};let time=0,ready=true,shots=0;const memory={};const root={document:doc,URLSearchParams,performance:{now:()=>time},navigator:{},location:{search:'',reload(){}},localStorage:{getItem:k=>memory[k]||null,setItem:(k,v)=>memory[k]=v,removeItem:k=>delete memory[k]},requestAnimationFrame(f){root.frame=f},alert(){}};vm.createContext(root);for(const n of ['ayar','veri','model3d','baraj','kaleci','ucus','fizik','puan','sevinc'])vm.runInContext(fs.readFileSync(__dirname+'/../js/'+n+'.js','utf8'),root);const D=root.DT;D.cizim={ciz(){},kur(){},sahneKur(){},kameraDurus(){},kamDurus:()=>0,hazir:()=>ready,boyut:()=>({w:390,h:844}),ekranToKale:(x,y)=>({x:x/100,y:y/100})};D.ses={ayarla(){},cal(){}};
let callback,state={room:{id:'test',code:'ABC123'},players:[]};function records(){let r={};state.players.forEach(p=>r[p.player]={id:p.player,idx:p.idx,puan:p.entries.reduce((a,e)=>a+e.puan,0),gol:p.entries.filter(e=>e.gol).length,yesil:p.entries.filter(e=>e.yesil).length});return r;}
D.live={identity:()=>({player:'meto'}),init(cb){callback=cb;cb(state);return Promise.resolve(state)},ensure:()=>Promise.resolve(state),current:()=>state.players[0],allowed:()=>true,getState:()=>state,records,async join(player){if(!state.players[0])state.players=[{player,idx:0,entries:[],mine:true}];return state.players[0]},async shot(player,idx,input){shots++;const p=D.puan.puanla(input.pos,D.fizik.hesapla(input));const physics=D.fizik.hesapla(input);const entry={ad:input.pos.ad,sonuc:physics.sonuc,puan:D.puan.puanla(input.pos.tip,physics).puan,gol:['gol','direk_gol'].includes(physics.sonuc),yesil:physics.bandaGirdi,input:{...input,rules:9}};state.players[0].entries.push(entry);state.players[0].idx++;callback(state);return entry},create:()=>Promise.resolve(state),link:()=>''};
vm.runInContext(fs.readFileSync(__dirname+'/../js/oyun.js','utf8'),root);D.oyun.baslat();const d=D.oyun._durum;function fire(id,k,v={}){for(const f of el(id).events[k]||[])f.call(el(id),v)}async function flush(){for(let i=0;i<6;i++)await Promise.resolve();}
fire('btnResmi','click');await flush();
for(let i=0;i<10;i++){
 assert.equal(d.idx,i);assert.equal(d.faz,'nisan');assert(!el('fifaNisan').hidden,'pozisyon açılınca doğrudan 1/3 yön adımı');
 assert(d.durusHazir&&!el('fifaNisan').hidden,'duruş ve nişan aynı ekranda (1/3), ayrı düğme/bekleme yok');assert.equal(d.durus,0,'başlangıçta düz duruş');
 {
  // FIFA tarzı atış (penaltı, frikik ve hedef ağı aynı): güç paneli yok; okla nişan → kilitle → falso → basılı tut-bırak güç → yeşilde bas.
  assert(el('gucPanel').hidden,'güç paneli yok');assert(!el('fifaNisan').hidden);assert(d.gucHazir);assert(d.aim&&d.aim.x===0&&d.aim.y===(d.pos.tip==='penalti'?1.3:1.6));
  fire('sahne','pointerdown',{clientX:105,clientY:65,pointerId:1});fire('sahne','pointerup');assert(!d.kilit,'kaleye dokunmak FIFA modunda kilitlemez');const x0=d.aim.x;
  fire('nisanSag','pointerdown',{pointerId:4,preventDefault(){}});for(let k=0;k<31;k++){time+=16;root.frame();}fire('nisanSag','pointerup');const beklenen=3.2*(.48+1.2*.48*.48);assert(Math.abs(d.aim.x-x0-beklenen)<.25,'0,5 sn sağ ok ≈2,4 m (basılı tuttukça hızlanır): '+(d.aim.x-x0));assert.equal(d.durus,0,'nişan oku duruşu değiştirmez (vücut ve nişan ayrı)');
  fire('nisanYukari','pointerdown',{pointerId:5,preventDefault(){}});for(let k=0;k<400;k++){time+=16;root.frame();}fire('nisanYukari','pointerup');assert.equal(d.aim.y,3.1,'üst sınır');
  fire('nisanAsagi','pointerdown',{pointerId:6,preventDefault(){}});for(let k=0;k<25;k++){time+=16;root.frame();}fire('nisanAsagi','pointerup');assert(d.aim.y<2.3&&d.aim.y>1.9,'aşağı ok: '+d.aim.y);
  fire('nisanKilit','click');assert(d.kilit);assert(el('fifaNisan').hidden);assert(!el('temasPanel').hidden);
  fire('vurBtn','pointerdown',{isPrimary:true});assert.equal(shots,i);assert(!d.fifa.faz,'falso seçilmeden sayaç başlamaz');
  fire('temasTop','pointerdown',{clientX:170,clientY:120,pointerId:2});fire('temasTop','pointerup');assert(d.temasHazir,'topa dokunup bırakınca doğrudan sertlik adımına geçer (2/3 → 3/3)');assert(!el('alt').hidden);assert(!el('fifaKutu').hidden);assert(el('cubukKutu').hidden);
  if(i===5){fire('duzeltBtn','click');assert(!el('fifaNisan').hidden);assert(!d.kilit);fire('nisanKilit','click');fire('temasOnay','click');}
  fire('vurBtn','pointerdown',{isPrimary:true});assert.equal(d.fifa.faz,'guc');time+=550;root.frame();fire('vurBtn','pointerup');assert.equal(d.fifa.faz,'isabet');assert(Math.abs(d.guc-.65)<.02,'yarım dolu güç ≈%65: '+d.guc);assert.equal(shots,i,'bırakmak vurmaz');
  if(i===6){time+=1500;root.frame();assert.notEqual(d.faz,'gonderiliyor','ibre aşağı indi ve geri dönüyor: hâlâ ikinci şans');time+=300;root.frame();assert.equal(d.faz,'gonderiliyor','iki geçiş de bitince en kötü zamanlamayla vurulur');}
  else if(i===4){time+=1000;root.frame();assert.equal(d.faz,'nisan','ibre 1,0 sn: ikinci geçişte, hâlâ vurulmadı');time+=200;fire('vurBtn','pointerdown',{isPrimary:true});assert.equal(d.faz,'gonderiliyor','ikinci geçişte (geri dönerken) de vurulabilir');}
  else{time+=400;fire('vurBtn','pointerdown',{isPrimary:true});assert.equal(d.faz,'gonderiliyor');}
  fire('vurBtn','pointerdown',{isPrimary:true});assert.equal(shots,i+1);
 }
 await flush();assert.equal(d.faz,'vurus');time+=15000;root.frame();assert.equal(d.faz,'sonuc');fire('devamBtn','click');}

assert.deepEqual(state.players[0].entries.map(e=>e.input.zaman),[.5,.5,.5,.5,.5,.5,0,.5,.5,.5],'FIFA ibresi zamanlamayı verir: 4. vuruş ikinci geçişte (geri dönerken) yeşilde, 7. vuruş iki geçiş de bitince en kötü zamanlama (0)');assert(state.players[0].entries.every(e=>Math.abs(e.input.guc-.65)<.02&&e.input.aim.y<2.3));
assert.equal(state.players[0].idx,10);assert.equal(state.players[0].entries.length,10);assert.equal(shots,10);assert.equal(d.ekran,'tursonu');assert(el('turNot').textContent.includes('otomatik'));console.log('PASS live cup flow; approach→3D walk→power→target→contact→timing; server wait; duplicate-press guard; ten automatic saves; result screen');
})().catch(e=>{console.error(e);process.exit(1)});
